import { db } from './client';
import { boostDefinitions, listings, users } from './schema';

export async function seedDatabase() {
  // Seed boost definitions
  await db.insert(boostDefinitions).values([
    { key: 'tier_upgrade', label: 'Tier Upgrade', description: 'Offer a premium sitter tier', icon: 'star.fill', sortOrder: 1 },
    { key: 'food_shop', label: 'Food Shop', description: 'Cover the cost of pet food', icon: 'cart.fill', sortOrder: 2 },
    { key: 'transport', label: 'Transport', description: 'Cover travel costs', icon: 'car.fill', sortOrder: 3 },
    { key: 'gift', label: 'Gift', description: 'Send a thank-you gift', icon: 'gift.fill', sortOrder: 4 },
    { key: 'custom', label: 'Custom Perk', description: 'Add your own perk', icon: 'plus.circle.fill', sortOrder: 5 },
  ]).onConflictDoNothing();

  // Seed mock users
  await db.insert(users).values([
    {
      externalId: 'mock-owner-1',
      name: 'Sophie Clarke',
      avatarUrl: 'https://i.pravatar.cc/150?img=47',
      role: 'owner',
      bio: 'Dog mum of two golden retrievers. Love travelling!',
      rating: 4.9,
      reviewCount: 23,
    },
    {
      externalId: 'mock-sitter-1',
      name: 'James Harwood',
      avatarUrl: 'https://i.pravatar.cc/150?img=12',
      role: 'sitter',
      sitterTier: 'paid',
      bio: 'Experienced pet sitter. 5 years, 80+ sits completed.',
      rating: 5.0,
      reviewCount: 81,
    },
  ]).onConflictDoNothing();

  // Seed mock listings — spread across interesting global locations
  const mockListings = [
    {
      ownerId: 1,
      title: 'Sunlit Kensington Flat',
      description: 'Bright and airy flat in the heart of London.',
      address: '14 Holland Park Ave, London',
      latitude: 51.5074,
      longitude: -0.2001,
      city: 'London',
      country: 'UK',
      bedrooms: 2,
      bathrooms: 1,
      amenities: JSON.stringify(['wifi', 'garden', 'parking']),
      petCount: 1,
      petTypes: JSON.stringify(['dog']),
      coverPhotoUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800',
      photos: JSON.stringify([
        'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800',
        'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800',
      ]),
    },
    {
      ownerId: 1,
      title: 'Provençal Stone Farmhouse',
      description: 'Charming farmhouse surrounded by lavender fields.',
      address: 'Route de Gordes, Provence',
      latitude: 43.8367,
      longitude: 5.3106,
      city: 'Provence',
      country: 'France',
      bedrooms: 4,
      bathrooms: 2,
      amenities: JSON.stringify(['pool', 'garden', 'wifi', 'fireplace']),
      petCount: 2,
      petTypes: JSON.stringify(['cat', 'cat']),
      coverPhotoUrl: 'https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=800',
      photos: JSON.stringify([
        'https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=800',
      ]),
    },
    {
      ownerId: 1,
      title: 'Tribeca Loft with Rooftop',
      description: 'Stylish loft in New York\'s most desirable neighbourhood.',
      address: '56 Franklin St, New York',
      latitude: 40.7195,
      longitude: -74.0089,
      city: 'New York',
      country: 'USA',
      bedrooms: 2,
      bathrooms: 2,
      amenities: JSON.stringify(['wifi', 'rooftop', 'gym']),
      petCount: 1,
      petTypes: JSON.stringify(['dog']),
      coverPhotoUrl: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
      photos: JSON.stringify([
        'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
      ]),
    },
    {
      ownerId: 1,
      title: 'Bondi Beach House',
      description: 'Steps from the sand with stunning ocean views.',
      address: '3 Campbell Parade, Bondi Beach',
      latitude: -33.8915,
      longitude: 151.2767,
      city: 'Sydney',
      country: 'Australia',
      bedrooms: 3,
      bathrooms: 2,
      amenities: JSON.stringify(['beach access', 'wifi', 'bbq', 'parking']),
      petCount: 2,
      petTypes: JSON.stringify(['dog', 'dog']),
      coverPhotoUrl: 'https://images.unsplash.com/photo-1523217582562-09d0def993a6?w=800',
      photos: JSON.stringify([
        'https://images.unsplash.com/photo-1523217582562-09d0def993a6?w=800',
      ]),
    },
    {
      ownerId: 1,
      title: 'Kyoto Machiya Townhouse',
      description: 'Traditional wooden townhouse in historic Gion district.',
      address: 'Gion, Kyoto',
      latitude: 35.0037,
      longitude: 135.7767,
      city: 'Kyoto',
      country: 'Japan',
      bedrooms: 2,
      bathrooms: 1,
      amenities: JSON.stringify(['wifi', 'garden', 'onsen nearby']),
      petCount: 1,
      petTypes: JSON.stringify(['cat']),
      coverPhotoUrl: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=800',
      photos: JSON.stringify([
        'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=800',
      ]),
    },
    {
      ownerId: 1,
      title: 'Santorini Clifftop Villa',
      description: 'Iconic whitewashed villa with caldera sunset views.',
      address: 'Oia, Santorini',
      latitude: 36.4618,
      longitude: 25.3753,
      city: 'Santorini',
      country: 'Greece',
      bedrooms: 3,
      bathrooms: 2,
      amenities: JSON.stringify(['infinity pool', 'wifi', 'sea view']),
      petCount: 1,
      petTypes: JSON.stringify(['cat']),
      coverPhotoUrl: 'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?w=800',
      photos: JSON.stringify([
        'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?w=800',
      ]),
    },
    {
      ownerId: 1,
      title: 'Brooklyn Brownstone',
      description: 'Classic brownstone with private garden in Park Slope.',
      address: '245 7th Ave, Brooklyn',
      latitude: 40.6690,
      longitude: -73.9796,
      city: 'Brooklyn',
      country: 'USA',
      bedrooms: 3,
      bathrooms: 2,
      amenities: JSON.stringify(['garden', 'wifi', 'washer']),
      petCount: 2,
      petTypes: JSON.stringify(['dog', 'cat']),
      coverPhotoUrl: 'https://images.unsplash.com/photo-1555636222-cae831e670b3?w=800',
      photos: JSON.stringify([
        'https://images.unsplash.com/photo-1555636222-cae831e670b3?w=800',
      ]),
    },
    {
      ownerId: 1,
      title: 'Edinburgh New Town Apartment',
      description: 'Georgian elegance with Arthur\'s Seat views.',
      address: '12 Heriot Row, Edinburgh',
      latitude: 55.9567,
      longitude: -3.2007,
      city: 'Edinburgh',
      country: 'UK',
      bedrooms: 2,
      bathrooms: 1,
      amenities: JSON.stringify(['wifi', 'fireplace', 'central location']),
      petCount: 1,
      petTypes: JSON.stringify(['dog']),
      coverPhotoUrl: 'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=800',
      photos: JSON.stringify([
        'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=800',
      ]),
    },
    {
      ownerId: 1,
      title: 'Barcelona Eixample Penthouse',
      description: 'Modernist-influenced penthouse with private terrace.',
      address: 'Carrer de Provença 248, Barcelona',
      latitude: 41.3937,
      longitude: 2.1628,
      city: 'Barcelona',
      country: 'Spain',
      bedrooms: 3,
      bathrooms: 2,
      amenities: JSON.stringify(['terrace', 'wifi', 'pool', 'gym']),
      petCount: 1,
      petTypes: JSON.stringify(['cat']),
      coverPhotoUrl: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800',
      photos: JSON.stringify([
        'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800',
      ]),
    },
    {
      ownerId: 1,
      title: 'Cape Town Clifton Retreat',
      description: 'Clifftop retreat with direct Atlantic Ocean access.',
      address: '4th Beach, Clifton, Cape Town',
      latitude: -33.9389,
      longitude: 18.3773,
      city: 'Cape Town',
      country: 'South Africa',
      bedrooms: 4,
      bathrooms: 3,
      amenities: JSON.stringify(['beach access', 'pool', 'wifi', 'mountain views']),
      petCount: 2,
      petTypes: JSON.stringify(['dog', 'dog']),
      coverPhotoUrl: 'https://images.unsplash.com/photo-1580537659466-0a9bfa916a54?w=800',
      photos: JSON.stringify([
        'https://images.unsplash.com/photo-1580537659466-0a9bfa916a54?w=800',
      ]),
    },
  ];

  await db.insert(listings).values(mockListings).onConflictDoNothing();
}
